create schema if not exists extensions;
create extension if not exists pg_trgm with schema extensions;

create table if not exists app_settings (
  key text primary key,
  value text not null,
  updated_at timestamptz not null default now()
);

insert into app_settings (key, value)
values ('owner_email', 'owner@example.com')
on conflict (key) do nothing;

create table if not exists people (
  id bigint generated by default as identity primary key,
  full_name text not null check (length(trim(full_name)) > 0),
  first_name text,
  last_name text,
  birthdate date,
  birthday_md text check (birthday_md is null or birthday_md ~ '^\d{2}-\d{2}$'),
  city text,
  country text,
  current_org text,
  "current_role" text,
  linkedin_url text,
  tie_strength smallint check (tie_strength between 1 and 5),
  met_where text,
  met_when text,
  summary text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists people_name_trgm_idx
  on people using gin (lower(full_name) extensions.gin_trgm_ops);
create index if not exists people_org_idx on people (current_org);
create index if not exists people_city_idx on people (city);

create table if not exists identifiers (
  person_id bigint not null references people(id) on delete cascade,
  kind text not null check (length(trim(kind)) > 0),
  value text not null check (length(trim(value)) > 0),
  is_primary boolean not null default false,
  source text not null default 'manual',
  observed_at date not null default current_date,
  primary key (kind, value)
);

create index if not exists identifiers_person_idx on identifiers(person_id);

create table if not exists orgs (
  id bigint generated by default as identity primary key,
  name text not null unique check (length(trim(name)) > 0),
  kind text,
  domain text,
  city text,
  country text,
  note text,
  created_at timestamptz not null default now()
);

create index if not exists orgs_name_trgm_idx
  on orgs using gin (lower(name) extensions.gin_trgm_ops);

create table if not exists affiliations (
  person_id bigint not null references people(id) on delete cascade,
  org_id bigint not null references orgs(id) on delete cascade,
  role text not null default '',
  since date,
  until date,
  source text not null default 'manual',
  observed_at date not null default current_date,
  primary key (person_id, org_id, role),
  check (until is null or since is null or until >= since)
);

create index if not exists affiliations_org_idx on affiliations(org_id);

create table if not exists edges (
  a_id bigint not null references people(id) on delete cascade,
  b_id bigint not null references people(id) on delete cascade,
  kind text not null check (length(trim(kind)) > 0),
  strength smallint check (strength between 1 and 5),
  since date,
  until date,
  note text,
  source text not null default 'manual',
  observed_at date not null default current_date,
  primary key (a_id, b_id, kind),
  check (a_id <> b_id),
  check (until is null or since is null or until >= since)
);

create index if not exists edges_b_idx on edges(b_id, kind);

create or replace function canonicalize_symmetric_edge()
returns trigger
language plpgsql
as $$
declare
  original_a bigint;
begin
  if new.kind in (
    'friend', 'family', 'partner', 'colleague', 'knows', 'classmate',
    'sibling', 'neighbor', 'neighbour'
  ) and new.a_id > new.b_id then
    original_a := new.a_id;
    new.a_id := new.b_id;
    new.b_id := original_a;
  end if;
  return new;
end;
$$;

drop trigger if exists edges_canonicalize_symmetric on edges;
create trigger edges_canonicalize_symmetric
before insert or update of a_id, b_id, kind on edges
for each row execute function canonicalize_symmetric_edge();

create table if not exists facts (
  id bigint generated by default as identity primary key,
  person_id bigint not null references people(id) on delete cascade,
  key text not null check (length(trim(key)) > 0),
  value text,
  num double precision,
  date date,
  source text not null default 'manual',
  observed_at date not null default current_date,
  confidence text not null default 'stated'
    check (confidence in ('stated', 'observed', 'inferred')),
  created_at timestamptz not null default now()
);

create index if not exists facts_person_idx on facts(person_id);
create index if not exists facts_key_idx on facts(key);

create table if not exists interactions (
  id bigint generated by default as identity primary key,
  person_id bigint not null references people(id) on delete cascade,
  happened_on date not null,
  channel text,
  summary text,
  source text not null default 'manual',
  created_at timestamptz not null default now()
);

create index if not exists interactions_person_date_idx
  on interactions(person_id, happened_on desc);

create table if not exists deleted_records (
  id bigint generated by default as identity primary key,
  record_type text not null,
  record_id bigint not null,
  payload jsonb not null,
  deleted_at timestamptz not null default now()
);

create or replace function touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists people_touch_updated_at on people;
create trigger people_touch_updated_at
before update on people
for each row execute function touch_updated_at();

drop view if exists stale cascade;
drop view if exists about cascade;
drop view if exists at_org cascade;
drop view if exists friends cascade;
drop view if exists network cascade;
drop view if exists rel cascade;
drop view if exists person cascade;

create view person
with (security_invoker = true)
as
select p.*,
       case
         when p.birthdate is not null then
           extract(year from age(current_date, p.birthdate))::int
       end as age,
       (select max(i.happened_on) from interactions i where i.person_id = p.id) as last_contact,
       current_date - coalesce(
         (select max(i.happened_on) from interactions i where i.person_id = p.id),
         p.created_at::date
       ) as days_since_contact
from people p;

create view rel
with (security_invoker = true)
as
select e.a_id as person_id, e.b_id as other_id, e.kind, e.strength,
       e.since, e.until, e.note, e.source, e.observed_at
from edges e
union all
select e.b_id, e.a_id, e.kind, e.strength,
       e.since, e.until, e.note, e.source, e.observed_at
from edges e
where e.kind in (
  'friend', 'family', 'partner', 'colleague', 'knows', 'classmate',
  'sibling', 'neighbor', 'neighbour'
);

create view network
with (security_invoker = true)
as
select pa.full_name as "of",
       r.kind as via,
       pb.full_name as name,
       pb.age,
       pb.current_org as org,
       pb."current_role" as role,
       pb.city,
       pb.tie_strength,
       pb.days_since_contact,
       r.strength as link_strength,
       pb.id
from rel r
join people pa on pa.id = r.person_id
join person pb on pb.id = r.other_id;

create view friends
with (security_invoker = true)
as select * from network where via = 'friend';

create view at_org
with (security_invoker = true)
as
select o.name as org, p.full_name as name, a.role, a.since, a.until,
       (a.until is null) as current, p.tie_strength, p.days_since_contact, p.id
from affiliations a
join orgs o on o.id = a.org_id
join person p on p.id = a.person_id;

create view about
with (security_invoker = true)
as
select p.full_name as name, f.key, f.value, f.num, f.date,
       f.source, f.observed_at, f.confidence, p.id
from facts f join people p on p.id = f.person_id;

create view stale
with (security_invoker = true)
as
select full_name as name, current_org as org, tie_strength,
       last_contact, days_since_contact, id
from person
where tie_strength >= 3;

create or replace function find_intro_paths(
  start_name text,
  target_org text,
  max_depth integer default 3
)
returns table (
  route text,
  depth integer,
  target_person_id bigint,
  target_person text,
  organization text
)
language sql
stable
as $$
  with recursive paths(person_id, depth, route_ids, route_names) as (
    select p.id, 0, array[p.id]::bigint[], array[p.full_name]::text[]
    from people p
    where lower(p.full_name) = lower(start_name)

    union all

    select r.other_id,
           paths.depth + 1,
           paths.route_ids || r.other_id,
           paths.route_names || next_person.full_name
    from paths
    join rel r on r.person_id = paths.person_id
    join people next_person on next_person.id = r.other_id
    where paths.depth < least(greatest(max_depth, 1), 5)
      and not (r.other_id = any(paths.route_ids))
  )
  select array_to_string(paths.route_names, ' -> '),
         paths.depth,
         p.id,
         p.full_name,
         o.name
  from paths
  join people p on p.id = paths.person_id
  join affiliations a on a.person_id = p.id and a.until is null
  join orgs o on o.id = a.org_id
  where lower(o.name) = lower(target_org)
    and paths.depth > 0
  order by paths.depth, p.full_name
  limit 20;
$$;

create or replace function delete_person(p_id bigint)
returns boolean
language plpgsql
security invoker
as $$
declare
  snapshot jsonb;
begin
  select jsonb_build_object(
    'person', to_jsonb(p),
    'identifiers', coalesce((select jsonb_agg(to_jsonb(i)) from identifiers i where i.person_id = p_id), '[]'::jsonb),
    'affiliations', coalesce((select jsonb_agg(to_jsonb(a)) from affiliations a where a.person_id = p_id), '[]'::jsonb),
    'facts', coalesce((select jsonb_agg(to_jsonb(f)) from facts f where f.person_id = p_id), '[]'::jsonb),
    'interactions', coalesce((select jsonb_agg(to_jsonb(x)) from interactions x where x.person_id = p_id), '[]'::jsonb),
    'edges', coalesce((select jsonb_agg(to_jsonb(e)) from edges e where e.a_id = p_id or e.b_id = p_id), '[]'::jsonb)
  )
  into snapshot
  from people p
  where p.id = p_id;

  if snapshot is null then
    return false;
  end if;

  insert into deleted_records (record_type, record_id, payload)
  values ('person', p_id, snapshot);
  delete from people where id = p_id;
  return true;
end;
$$;
